// ============================================================================
//  wire-sprites.mjs — turn fetched renders into SPRITES registry entries
// ============================================================================
// Reads scripts/sprite-manifest.json (written by fetch-sprites.mjs) and regenerates the block
// between the RENDER-SPRITES markers in artifacts/V1/index.html, plus the render inventory in
// assets/sprites/CREDITS.md.
//
//   node scripts/wire-sprites.mjs
//
// Only fighters whose render was ACCEPTED are wired. A rejected fighter is left with no entry at
// all, which is the correct outcome: it keeps the drawn look it already had.

import { readFileSync, writeFileSync } from 'node:fs';

const MONOLITH = 'artifacts/V1/index.html';
const CREDITS = 'artifacts/V1/assets/sprites/CREDITS.md';
const MANIFEST = 'scripts/sprite-manifest.json';
const START = '/* RENDER-SPRITES-START */';
const END = '/* RENDER-SPRITES-END */';
const CRED_START = '<!-- RENDER-INVENTORY-START -->';
const CRED_END = '<!-- RENDER-INVENTORY-END -->';

const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
const accepted = Object.values(manifest).filter(r => r.ok).sort((a, b) => a.name.localeCompare(b.name));

// A very tall, narrow render (Needle) would be contain-fitted by height and end up a sliver; a very
// wide one (Coiny) by width. The defaults handle both, but an extreme aspect gets a nudge so the
// character reads at a comparable visual size to the rest of the cast.
// The contain-fit means a very WIDE character is capped by width and ends up drawing short — at
// the default box Bracelety (aspect 1.79) and Naily (1.70) came out 1.45R and 1.53R tall against a
// cast averaging ~2.4R, so they read as half-size rather than as wide. Widening their box restores
// comparable apparent SIZE (geometric mean of drawn width and height) without stretching anything,
// since the image's own aspect ratio still decides the shape.
// FACING OVERRIDES — set by eye, and they win over the measurement.
//
// The automated facing check finds the centroid of interior dark ink and assumes it is the face.
// That is wrong for any character with dark DECORATION on the opposite side from their face, and
// it produced real, visible bugs: Money's "5" and his dark money-clip sit left of his face and
// dragged the centroid with them, so he was flipped and walked backwards. A later eye-detecting
// heuristic missed him too.
//
// The tell that settles it: Money's "5" reads BACKWARDS when mirrored. A render carrying legible
// text or numerals must never be flipped, whatever any centroid says.
const FACING_OVERRIDE = {
  'money.png': false,   // face is on the right; the "5" and clip are decoration, and mirror illegibly
  'fanny.png': false,   // face is on the right; the blue handle is what the ink check latched onto
};

function box(r) {
  const ar = r.width / r.height;
  const o = {};
  if (r.file in FACING_OVERRIDE) {
    if (FACING_OVERRIDE[r.file]) o.flip = true;
    if (ar < 0.45) o.imgH = 3.1;
    else if (ar > 1.5) o.imgW = 3.2;
    else if (ar > 1.15) o.imgW = 2.6;
    return o;
  }
  if (ar < 0.45) o.imgH = 3.1;             // sliver characters stand a little taller
  if (ar > 1.5) o.imgW = 3.2;              // very wide characters get real room sideways
  else if (ar > 1.15) o.imgW = 2.6;        // squat characters get a little
  if (r.flip) o.flip = true;
  return o;
}

const lines = accepted.map(r => {
  const o = box(r);
  const opts = Object.keys(o).length
    ? `, { ${Object.entries(o).map(([k, v]) => `${k}:${v}`).join(', ')} }`
    : '';
  const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(r.name) ? r.name : JSON.stringify(r.name);
  return `  ${key}: renderSprite(${JSON.stringify(r.file)}${opts}),   // ${r.width}x${r.height}, facing ${r.facing}`;
});

const block = [
  `  // ---- official character renders (generated by scripts/wire-sprites.mjs — do not hand-edit) ----`,
  `  // ${accepted.length} fighters. Each falls back to the generic blob until its PNG decodes, and`,
  `  // forever if the file is missing. Facing was measured, not eyeballed — see fetch-sprites.mjs.`,
  ...lines,
].join('\n');

let html = readFileSync(MONOLITH, 'utf8');
const i = html.indexOf(START), j = html.indexOf(END);
if (i < 0 || j < 0) throw new Error(`markers not found in ${MONOLITH}`);
html = html.slice(0, i + START.length) + '\n' + block + '\n' + html.slice(j);
writeFileSync(MONOLITH, html);

// ---- credits ----------------------------------------------------------------------------------
const rows = [
  '',
  `**${accepted.length} additional character renders**, fetched from the character infobox on`,
  '`battlefordreamisland.fandom.com` via the MediaWiki API, scaled server-side to 200px tall, PNG',
  'with verified alpha and the invisible halo erased. Same provenance as the twelve above:',
  "jacknjellify's character artwork, no formal license, used under fan-work norms in a disclaimed,",
  'non-commercial fan game.',
  '',
  '| Fighter | File | Size | Facing | Source |',
  '|---|---|---|---|---|',
  ...accepted.map(r =>
    `| ${r.name} | \`${r.file}\` | ${r.width}×${r.height} | ${r.facing}${r.flip ? ' (flipped)' : ''} | ${r.source} |`),
  '',
].join('\n');

let cred = readFileSync(CREDITS, 'utf8');
if (cred.includes(CRED_START)) {
  const a = cred.indexOf(CRED_START), b = cred.indexOf(CRED_END);
  cred = cred.slice(0, a + CRED_START.length) + '\n' + rows + cred.slice(b);
} else {
  cred += `\n\n## Additional renders\n\n${CRED_START}\n${rows}${CRED_END}\n`;
}
writeFileSync(CREDITS, cred);

console.log(`wired ${accepted.length} render entries into ${MONOLITH}`);
for (const r of accepted) console.log(`  ${r.name.padEnd(14)} ${r.file}`);
const rejected = Object.values(manifest).filter(r => !r.ok);
if (rejected.length) {
  console.log(`\n${rejected.length} left with their drawn look:`);
  for (const r of rejected) console.log(`  ${r.name.padEnd(14)} ${r.reason}`);
}
